//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountDown.Application.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CountDown.Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This applictaion is create for my mom. O(∩_∩)O~.
        /// </summary>
        public static string AboutMessage {
            get {
                return ResourceManager.GetString("AboutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlertTime is mandatory.
        /// </summary>
        public static string AlertTimeMandatory {
            get {
                return ResourceManager.GetString("AlertTimeMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minutes before Alert is mandatory..
        /// </summary>
        public static string BeforeAlertMinutesMandatory {
            get {
                return ResourceManager.GetString("BeforeAlertMinutesMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minutes before Alert must be between {1} and {2}..
        /// </summary>
        public static string BeforeAlertMinutesRange {
            get {
                return ResourceManager.GetString("BeforeAlertMinutesRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Alert days is mandatory..
        /// </summary>
        public static string DaysMandatory {
            get {
                return ResourceManager.GetString("DaysMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The count down days must be between {1} and {2}..
        /// </summary>
        public static string DaysRange {
            get {
                return ResourceManager.GetString("DaysRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minutes to set alert expired is mandatory..
        /// </summary>
        public static string ExpiredMinutesMandatory {
            get {
                return ResourceManager.GetString("ExpiredMinutesMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minutes to set alert expired must be between {1} and {2}..
        /// </summary>
        public static string ExpiredMinutesRange {
            get {
                return ResourceManager.GetString("ExpiredMinutesRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Alert hours is mandatory..
        /// </summary>
        public static string HoursMandatory {
            get {
                return ResourceManager.GetString("HoursMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The count down hours must be between {1} and {2}..
        /// </summary>
        public static string HoursRange {
            get {
                return ResourceManager.GetString("HoursRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Alert minutes is mandatory..
        /// </summary>
        public static string MinutesMandatory {
            get {
                return ResourceManager.GetString("MinutesMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The count down minute must be between {1} and {2}..
        /// </summary>
        public static string MinutesRange {
            get {
                return ResourceManager.GetString("MinutesRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notice branch is mandatory..
        /// </summary>
        public static string NoticeBranchMandatory {
            get {
                return ResourceManager.GetString("NoticeBranchMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        public static string NoticeFormat {
            get {
                return ResourceManager.GetString("NoticeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice is madatory..
        /// </summary>
        public static string NoticeMandatory {
            get {
                return ResourceManager.GetString("NoticeMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the application so that the configuration changes take effect..
        /// </summary>
        public static string RestartApplication {
            get {
                return ResourceManager.GetString("RestartApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get an error when save the data. Please contact me when this happend. Error message: {0}.
        /// </summary>
        public static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more settings not validate..
        /// </summary>
        public static string SettingError {
            get {
                return ResourceManager.GetString("SettingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sound path should be a absolute or relative path..
        /// </summary>
        public static string SoundPathError {
            get {
                return ResourceManager.GetString("SoundPathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sound path is required..
        /// </summary>
        public static string SoundPathMandatory {
            get {
                return ResourceManager.GetString("SoundPathMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time is mandatory..
        /// </summary>
        public static string TimeMandatory {
            get {
                return ResourceManager.GetString("TimeMandatory", resourceCulture);
            }
        }
    }
}
