//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountDown.Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CountDown.Presentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This applictaion is building for my mom. O(∩_∩)O~
        ///If anyone found any bugs in this program or any awesome ideas, please contanct me..
        /// </summary>
        public static string AboutMessage {
            get {
                return ResourceManager.GetString("AboutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _I know it.
        /// </summary>
        public static string AboutOK {
            get {
                return ResourceManager.GetString("AboutOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add.
        /// </summary>
        public static string AddCountDownData {
            get {
                return ResourceManager.GetString("AddCountDownData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add Branch.
        /// </summary>
        public static string AddNewBranch {
            get {
                return ResourceManager.GetString("AddNewBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alart Items:.
        /// </summary>
        public static string AlartItems {
            get {
                return ResourceManager.GetString("AlartItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert at.
        /// </summary>
        public static string AlertAtTimeTitle {
            get {
                return ResourceManager.GetString("AlertAtTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following items is alert:.
        /// </summary>
        public static string AlertList {
            get {
                return ResourceManager.GetString("AlertList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Time.
        /// </summary>
        public static string AlertTimeHeader {
            get {
                return ResourceManager.GetString("AlertTimeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        public static string ApplicationSettings {
            get {
                return ResourceManager.GetString("ApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Settings.
        /// </summary>
        public static string BranchSettings {
            get {
                return ResourceManager.GetString("BranchSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Browse....
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中文(_C).
        /// </summary>
        public static string ChineseMenu {
            get {
                return ResourceManager.GetString("ChineseMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Down Alert.
        /// </summary>
        public static string CountDownTab {
            get {
                return ResourceManager.GetString("CountDownTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Down In.
        /// </summary>
        public static string CountDownTimeTitle {
            get {
                return ResourceManager.GetString("CountDownTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create by: BigEgg.
        /// </summary>
        public static string CreateBy {
            get {
                return ResourceManager.GetString("CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time.
        /// </summary>
        public static string DateAndTime {
            get {
                return ResourceManager.GetString("DateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HH:mm.
        /// </summary>
        public static string DateString {
            get {
                return ResourceManager.GetString("DateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HH:mm (MM-dd).
        /// </summary>
        public static string DateStringWithDays {
            get {
                return ResourceManager.GetString("DateStringWithDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail: .
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cd_bigegg@hotmail.com.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _English.
        /// </summary>
        public static string EnglishMenu {
            get {
                return ResourceManager.GetString("EnglishMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string ExitMenu {
            get {
                return ResourceManager.GetString("ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play alert sound.
        /// </summary>
        public static string HasAlertSound {
            get {
                return ResourceManager.GetString("HasAlertSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got It.
        /// </summary>
        public static string IKnowIt {
            get {
                return ResourceManager.GetString("IKnowIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Queue:.
        /// </summary>
        public static string ItemsQueue {
            get {
                return ResourceManager.GetString("ItemsQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Language.
        /// </summary>
        public static string LanguageMenu {
            get {
                return ResourceManager.GetString("LanguageMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before Alert (min.).
        /// </summary>
        public static string NewAlertBeforeMinutes {
            get {
                return ResourceManager.GetString("NewAlertBeforeMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string NewCountDownDays {
            get {
                return ResourceManager.GetString("NewCountDownDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string NewCountDownHours {
            get {
                return ResourceManager.GetString("NewCountDownHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string NewCountDownMinutes {
            get {
                return ResourceManager.GetString("NewCountDownMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string NewItemBranch {
            get {
                return ResourceManager.GetString("NewItemBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        public static string NewItemNotice {
            get {
                return ResourceManager.GetString("NewItemNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        public static string NoticeHeader {
            get {
                return ResourceManager.GetString("NoticeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good to go..
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Remove.
        /// </summary>
        public static string RemoveBranch {
            get {
                return ResourceManager.GetString("RemoveBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset data after added.
        /// </summary>
        public static string ResetData {
            get {
                return ResourceManager.GetString("ResetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert At Time.
        /// </summary>
        public static string SetAlermTab {
            get {
                return ResourceManager.GetString("SetAlermTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before Alart.
        /// </summary>
        public static string SettingBeforeAlertMinutes {
            get {
                return ResourceManager.GetString("SettingBeforeAlertMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired Minutes.
        /// </summary>
        public static string SettingExpiredMinutes {
            get {
                return ResourceManager.GetString("SettingExpiredMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has alert sound.
        /// </summary>
        public static string SettingHasAlertSound {
            get {
                return ResourceManager.GetString("SettingHasAlertSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string ShowAboutDialogMenu {
            get {
                return ResourceManager.GetString("ShowAboutDialogMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Setting....
        /// </summary>
        public static string ShowSettingDialogMenu {
            get {
                return ResourceManager.GetString("ShowSettingDialogMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound path.
        /// </summary>
        public static string SoundPath {
            get {
                return ResourceManager.GetString("SoundPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That it i_s.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string TimeHeader {
            get {
                return ResourceManager.GetString("TimeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tools.
        /// </summary>
        public static string ToolsMenu {
            get {
                return ResourceManager.GetString("ToolsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unkonw error happend...%&gt;_&lt;%
        ///
        ///{0}.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
    }
}
